workloads:
  - type: PythonWorkload
    name: comms
    module: mqtt_update
    class: MqttUpdate
    tick_rate_hz: 30

  - type: PythonWorkload
    name: console
    module: console_update
    class: ConsoleUpdate
    tick_rate_hz: 2

  - type: SyncedPairWorkload
    name: motion_pair
    primary:
      type: PythonWorkload
      name: brickpi3_interface
      module: brickpi
      class: BrickPi3Interface
      tick_rate_hz: 100

    secondary:
      type: SequenceWorkload
      name: control_sequence
      children:
        - type: PythonWorkload
          name: remote_control
          module: remote
          class: RemoteControlInterface

        - type: PythonWorkload
          name: deadzone_transformer
          module: transform
          class: DeadZoneScaleAndSplitTransformer

        - type: PythonWorkload
          name: steering_mixer
          module: steering
          class: SteeringMixerTransformer
