workloads:

  - type: RemoteControlInterface

  - type: DeadZoneScaleAndSplitTransformer
    name: deadzone_transformer
    args:
      dead_zone: 0.2
      # scale_x: -0.15
      # scale_y: 0.4
      data_bindings:
        - input_vector <- remote_control_interface.left_stick
        - output_y -> steering_mixer.input_speed
        - output_x -> steering_mixer.input_turn_rate

  - type: SteeringMixerTransformer
    name: steering_mixer
    args:
      power_scale_both: 100.0
      data_bindings:
        - output_left_motor -> brickpi3_interface.motor_a_power
        - output_right_motor -> brickpi3_interface.motor_d_power

  - type: BrickPi3Interface
    name: brickpi3_interface
    args:
      tick_rate_hz: 100
      sensor_1_type: EV3_GYRO_ABS_DPS
      motor_a_enabled: 1
      motor_d_enabled: 1

  - type: MqttUpdate
    name: comms

  - type: ConsoleUpdate
    name: console
