name: Require Label for Main PRs

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check-label:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Fail if required label is missing
        uses: actions/github-script@v7
        with:
          script: |
            const requiredLabel = "approved-for-main";
            const labels = context.payload.pull_request.labels.map(label => label.name);
            if (!labels.includes(requiredLabel)) {
              core.setFailed(`Missing required label: ${requiredLabel}`);
            }
